### ISSUE TITLE
Updating dynamic pipeline job through watcher

### ISSUE THREAD

**Issue by smalleni** [cloud-bulldozer/scale-ci-pipeline#203]
Currently watcher is run as a part of the pipeline but if the dynamic jjb of the pipeline itself changes, the current pipeline execution remains unaffected. We would the pipeline job also to be updated in real time

**Comment by smalleni** [comment]
@chaitanyaenr If this is fixed please close it with a comment

**Comment by chaitanyaenr** [comment]
@smalleni Nice catch. This should be fixed, we now have a watcher job outside the pipeline which takes care of updating the jobs including the pipelines.
